# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0002_auto_20181013_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
